version: '3.8'
services:
  visitor-tracking:
    build:
      context: .
      target: builder
    environment:
      REDIS_URL: "redis:6379"
    volumes:
      - ./:/app
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - '8002:8002'